language: python
python:
- 2.7
- 3.4
- 3.5
- pypy3
install: pip install tox-travis
script: tox
matrix:
  allow_failures:
  - python: 2.7
  - python: pypy3
  include:
    - python: pypy3
      install: pip install tox-travis asyncio
deploy:
  provider: pypi
  user: aequitas
  password:
    secure: mMEurun9eAGn7Mtk9Rc6fwy82o3VFZJ8rQKy/w8NkRaFd3EYk3PsXv/bk8X1EjkuWCwNL700IJzj0NGyFI8/P367LW8MgbwywEPB0dGBxv+ttBy94hblfLYPGhtao1c7opZc8as7zpT/piSHzOd3UXzceHmupu+xG7pdzI74OIh0rh1HJ7mqf3vSjGAufS3knXBbAM1EW3obFfvJ3hT3uUZGlkgdXDKBLh/kpO5cinM/OwsogTrO0emYq8qKxcsku/8t15EHH5A7SQ5GuFoYGDNb4ubB1vmbKcgMdqEbE2Xaqb5q8sP7+YTuDNfsBw04SZpZsfFU6tVwIMiPgDl/bqcOuG1dAgbc7c0fYRi2eh+gq8K9tiudTR7j4XL2NhZcU5zY+VZT3c1LP+ZbUfc33zfL/Xzagep+mu1Spo6YkzTJ8P+v8x4AcMC7dPbH3AIZCkAj3RDUXW4wykGbELSPt9DuD+ZssNZfNi9xzpgWARpvDQ8/eX9twq7kuJBLoJaT8fi1Pu0QQ9HWdlQbPUj8Dohl+YOjZZFr9hG0lW42W1imHtC2sdkIU6byuySe1MjbedweENfeqmamCQ6z0BCw+MCZRs3JCO1ffwoQix9SCsIZCbFS2JEU+cvqk34gV3oBozByLf2DpHIU5FIsTgFxdenb3BUB2KQw9rHZb1WjdJ8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: aequitas/python-rflink
